version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
  api:
    build: ./AthleteApi/
    ports: 
      - 5274:80
    depends_on:
      - db
